version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}

  app:
    image: simple2b/flask-app:latest
    restart: always
    command: sh ./start_server.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`forum.simple2b.net`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls.certresolver=myresolver'
      - 'traefik.http.routers.web.tls=true'

  gate:
    image: traefik:v2.5
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    command:
      - '--log.level=DEBUG'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      # Certificates
      - '--entryPoints.websecure.address=:443'
      - '--entryPoints.web.address=:80'
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-simle2b.info@gmail.com}'
      - '--certificatesresolvers.myresolver.acme.storage=/data/acme.json'
      - '--certificatesresolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      # Redirects http -> https
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'

volumes:
  db_data:
