"""rooms_new

Revision ID: 625b9b59357d
Revises: f99dad6dba78
Create Date: 2023-09-18 10:48:51.470863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625b9b59357d'
down_revision = 'f99dad6dba78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_message_author_id_users')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_message_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    sa.UniqueConstraint('body', name=op.f('uq_message_body'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
