"""non_unique_message

Revision ID: 6bfcbef91c17
Revises: 625b9b59357d
Create Date: 2023-09-18 12:31:30.873568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfcbef91c17'
down_revision = '625b9b59357d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('uq_message_body', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_message_body', ['body'])

    # ### end Alembic commands ###
